### ISSUE TITLE
Is this gem still maintained? Alternatives?

### ISSUE THREAD

**Issue by gr8bit** [prawnpdf/prawn-table#121]
Sorry for asking the usual question but as the gem has almost as many open issues as closed ones, 25 open PRs and the latest commit to master was in 2017, I hope the maintainers don't mind.

Also, to all fellow Prawn table users: how do you deal with the issues you have with prawn-table?

Best

**Comment by pointlessone** [comment]
@gr8bit prawn-table is not actively worked on but is maintained. This means that PRs are welcome. I encourage everyone to submit a PR if they have an issue with prawn-table and ability to contribute.

---

I'll close this issue now. Feel free to reopen if you feel like your question has not been answered.
