### ISSUE TITLE
Missing matrix gem dependency

### ISSUE THREAD

**Issue by kg-currenxie** [prawnpdf/prawn-table#156]
```
       ...
       Fetching gem metadata from https://rubygems.org/.........
       Fetching racc 1.7.2
       Installing racc 1.7.2 with native extensions
       Fetching pdf-core 0.9.0
       Installing pdf-core 0.9.0
       Fetching ttfunk 1.7.0
       Installing ttfunk 1.7.0
       Fetching telephone_number 1.4.20
       Installing telephone_number 1.4.20
       Fetching prawn 2.4.0
       Installing prawn 2.4.0
       Fetching net-imap 0.4.3
       Fetching aws-sdk-core 3.185.2
       Installing net-imap 0.4.3
       Fetching prawn-table 0.2.2
       Installing aws-sdk-core 3.185.2
       Installing prawn-table 0.2.2
       Bundle complete! 74 Gemfile dependencies, 157 gems now installed.
       ...
       LoadError: cannot load such file -- matrix
```
Even tho, `prawn` has the dependency, somehow this breaks (when im deploying)

Adding `gem 'matrix'` manually to my gemfile makes it work.

Matrix was removed from core gems from Ruby 3.1

More info here
https://stackoverflow.com/questions/71991514/rails-require-cannot-load-such-file-matrix

**Comment by pointlessone** [comment]
Prawn 2.4.0 doesn't depend on `matrix`. This has been fixed in master branch. Though, not released yet.

---

I'm closing this as there's not much left to do but feel free to reopen if you have any additional details.

**Comment by Frexuz** [comment]
isn't is this? https://github.com/prawnpdf/prawn/blob/master/prawn.gemspec#L39

**Comment by pointlessone** [comment]
It is.
