### ISSUE TITLE
Strange Multi-Page Table Wrapping when a cell has multi-rowspan on the last row

### ISSUE THREAD

**Issue by Bharat311** [prawnpdf/prawn-table#3]
When having a multi page table, and the last row of the table has a rowspan > 1 then the following output is obtained.

![issue](https://cloud.githubusercontent.com/assets/1005808/3657352/01b8164a-1194-11e4-891d-f01634213a45.png)

**Comment by White-Oak** [comment]
This wasn't fixed in #16 as it wasn't merged

**Comment by ashiksp** [comment]
Any update on this ?
