### ISSUE TITLE
Allow render table in multiple pages

### ISSUE THREAD

**Issue by ccarruitero** [prawnpdf/prawn-table#51]
I can't find a way to draw a table in multiple pages when width is larger than a page.
So I tried to implement this.

I did a few changes in table's [draw method](https://github.com/ccarruitero/prawn-table/blob/multipage/lib/prawn/table.rb#L298)

And add a few [specs for this](https://github.com/ccarruitero/prawn-table/blob/multipage/spec/table_spec.rb#L948)

Apparently is ok and specs are passing right now, but table are not rendering. I get just a blank page.
Not sure what I'm missing.

I really appreciate if someone can give me a clue to get this feature.

**Comment by packetmonkey** [comment]
Feel free to open up a pull request with your changes so we can more easily see what the change looks like. Hopefully we can work it out and get your feature added.

Thanks! I'll close this issue in the mean time so we can follow the discussion up on the actual PR.
