### ISSUE TITLE
:shrink_to_fit vs Hash / :cell_style => { :overflow => :shrink_to_fit } being ignored?

### ISSUE THREAD

**Issue by dangoldgriff** [prawnpdf/prawn-table#58]
Hi @jordanbyron, @packetmonkey, @practicingruby!
As i'm not sure what the best solution will be here I thought i'd try to ping all of you at once. 

I have a two part issue/request/question:

This started with truncation issues in prawn-labels: a string being inserted was roughly ~60 characters, causing label formats to break. 

The data format I am passing to `Prawn::Labels.generate` is a Hash, and the split method inside `shrink_text` freaks out on the Hash. First question:
1. Have you seen this question before? Is there a succinct work around or suggestion any of you may have to help work through this? (Imo using the method in prawn-labels is the best thing to do.)

2. Upon noticing truncation issues I delved into prawn-table:
- the `overflow => :shrink_to_fit` argument inside `pdf.make_table(label_data[:data_table], :cell_style => { :overflow => :shrink_to_fit, :size => 6, :border_width => 0.1 }, :position => :right)` is being ignored. To my understanding the `:cell_style` option block passed to make table is in a valid format with valid arguments, but again when a string of ~60 characters makes its way in the `shrink_to_fit` is  ignored, causing a label "breaking" layout. 

I hope i've given enough information to find some sort of solution! If you have any questions for me don't hesitate to reach me here or on Twitter @dangoldgriff. 

Cheers!

**Comment by jordanbyron** [comment]
@dangoldgriff can you write up a quick failing code example that I can run? That would help me pinpoint what's going on here. Thanks!

**Comment by dangoldgriff** [comment]
@jordanbyron Will post code shortly! Also a quick question, and perhaps there's some misinterpretation on my part about how `:overflow => :shrink_to_fit` works. Could you explain what that argument does if it is supplied?

**Comment by jordanbyron** [comment]
@dangoldgriff I just realized you opened this issue on the `prawn-table` tracker and you are actually having issues with `prawn-labels`. You should probably be reporting this over here: https://github.com/jordanbyron/prawn-labels/issues/

**Comment by dangoldgriff** [comment]
@jordanbyron :dizzy_face: Duly noted. Was under the impression `:cell_style => { :overflow => :shrink_to_fit}` was a part of prawn-table. Will reopen shortly.

**Comment by dangoldgriff** [comment]
@jordanbyron Just for full disclosure that code came from here: 
`pdf.table(label_table, :width => label_width, :cell_style => { :overflow => :shrink_to_fit, :inline_format => true }) do
          row(0).borders = []
          cells[0,0].height = label_height
          row(0).column(0).padding = adjusted_padding
        end`

**Comment by jordanbyron** [comment]
@dangoldgriff I really think a code example would really help here, but based on your initial description this sounds like an issue with prawn-labels `shrink_text` method which is why I suggested you open this issue up on the prawn-lables tracker.
