### ISSUE TITLE
Remote images in table cells

### ISSUE THREAD

**Issue by knutigro** [prawnpdf/prawn-table#71]
From docs I understand that images should be in local folders on server. Loading remote images into table cells is not supported in current implementation. I can imagine this would even be quite weak on performance since I guess all images has to be loaded into memory before doing the PDF creation. 

Did anyone try to add this feature this yet? Do you think its hard to accomplish in Prawn and Prawn-Table? 

I am quite new to Ruby but I really need to do this in the app I am building. Maybe its possible to do some kind of workaround to accomplish this in Ruby on Rails? E.g. first saving the images in some temporary location before PDF creation. What do you think? 

If you think its possible and maybe help me with some ideas of what is the best approach, I would be happy to try putting something together myselves and deliver a pull request.

/knut

**Comment by pointlessone** [comment]
Hello Knut,

`image` method can take in IO-like objects. The object has to support at least `rewind` and `read`. So technically you can implement a streaming proxy object to a remote image.

Or you can store images locally and pass file path.

In either case it's going to be slow and it has to be implemented by you — our dear Prawn user.

I will now close the issue. Feel free to reopen if you have more feedback that can further the discussion.

**Comment by knutigro** [comment]
Great! thank you for quick response 👍 I will try to find a sollution and I think my first approach will be to try the saving images locally first.
