### ISSUE TITLE
who can help me make a table contains Arabic and English at the same time

### ISSUE THREAD

**Issue by imidsac** [prawnpdf/prawn-table#77]
Hi!
my problem is :  redirecte: :rtl and redirecte: :ltr in same cell.
my wish and do it like this : https://drive.google.com/file/d/0B8r7Uu63KbCBbTRyNWh5VmxZR28/view?usp=sharing

**Comment by imidsac** [comment]
I have this error: ``undefined method `direction=' for #<Prawn::Table::Cell::Text:0x007fb42f5ac428>``

**Comment by pointlessone** [comment]
> `undefined method `direction=' for #<Prawn::Table::Cell::Text:0x007fb42f5ac428>`

And rightly so. The class indeed has no such method.

You can try defining it.

```ruby
module Prawn
  class Table
    class Cell
      class Text
        def direction=(value)
          @text_options[:direction] = value
        end
      end
    end
  end
end
```

---

I will close this issue now.

It looks like this is an omission on the Prawn::Table part. Feel free to open a specific issue requesting to add this feature or even better a pool request for it.

**Comment by imidsac** [comment]
Thanks @pointlessone
