### ISSUE TITLE
Confusing intro in manual

### ISSUE THREAD

**Issue by matkoniecz** [prawnpdf/prawn-table#82]
"Prawn comes with table support out of the box." - as I understand, since prawn-table was extracted it is no longer true.

**Comment by pointlessone** [comment]
You're quite correct on this one.

**Comment by matkoniecz** [comment]
Fixing this requires changing https://github.com/prawnpdf/prawn-table/blob/8d33e892bdca2a82db01499d39c150e4d7b3bbea/manual/table/table.rb#L39

**Comment by matkoniecz** [comment]
#83 is a tiny PR that should fix this.

**Comment by pointlessone** [comment]
Thank you for your contribution. prawn-table maintainers will take a look when they have time. :)

**Comment by boykoc** [comment]
Looks like left-over wording from when prawn-table was part of prawn.
