### ISSUE TITLE
how to make colorful-box( progress bar) inside the table column

### ISSUE THREAD

**Issue by ramir2426** [prawnpdf/prawn-table#89]
like this please help me:
![screenshot from 2017-08-07 04-27-22](https://user-images.githubusercontent.com/25569450/29008041-4c0e8182-7b29-11e7-8581-888b0a7240ef.png)

**Comment by tilsammans** [comment]
Hi @ramir2426 

As this is not a bug, but a question, you should ask this on [StackOverflow](https://stackoverflow.com). Use the tags `prawn` and `prawn-table`.
